import pandas as pd
import os

configfile: "config/config.yaml"
include: "rules/common.py"

READ_SUBSAMPLES=set(config['read_subsamples'])

SAMPLES = [line.strip() for line in open(config['samples'], 'r')]
SAMPLE1 = SAMPLES[0]

TARGETS = [line.strip() for line in open(config['refs'], 'r')]

#container: "docker://sethnr/pgcoe_bacseq:0.01"

include: "rules/cplocal.smk"

include: "rules/align.smk"

include: "rules/ivar.smk"

#include: "rules/snippy.smk"

include: "rules/mykrobe.smk"

#include: "rules/lineage.smk"

localrules: all, cp_local_fq


rule all:
    input:
        combinedcoverage=os.path.join(config['outdir'],config['runname'],'combinedcoverage.tsv'),
        basedepth=config['outdir']+'/'+config['runname']+'/all_depth.txt',
        #pileupvcf=config['outdir']+'/'+config['runname']+'/pileup_all_vars.vcf.gz',
        #lineages="results/poppunk/complete"
        #lineages="results/srst/complete"
        mykrobecombined=config['outdir']+'/mykrobe/combined.csv'
        
        # evorha=expand(config['outdir']+'/evorha/{sample}.hapfreq',sample=SAMPLES),
        

rule coverage:
    input:
        subsamp=os.path.join(config['outdir'],'align/{sample}_subsamp{subsample}.bam')
    output:
        coveragestats=os.path.join(config['outdir'],'align/{sample}_coverage_sub{subsample}.tsv')
    resources:
        mem_mb=8000,
        runtime=180,
    params:
        maxdepth=0,
        minmapqual=60,
        minbasequal=13
    container: "docker://sethnr/pgcoe_bacseq:0.01"
    log:
        stderr="logs/align/{sample}_sub{subsample}.err"
    message: "Computing coverage of reference for sample {wildcards.sample} with a read subsample fraction of {wildcards.subsample}"
    shell:
        """
        printf '%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n' {wildcards.sample} {wildcards.subsample} `samtools coverage -d {params.maxdepth} -q {params.minmapqual} -Q {params.minbasequal} --no-header {input.subsamp}` > {output.coveragestats} 2> {log.stderr}
        """

rule mdepth:
    input:
        bams=expand(os.path.join(config['outdir'],'align/{sample}_aln_itrim_sorted.bam'),sample=SAMPLES)
    output:
        config['outdir']+'/'+config['runname']+'/all_depth.txt'
    resources:
        mem_mb=8000,
        runtime=180,
    params:
        maxdepth=0,
        minmapqual=60,
        minbasequal=13
    container: "docker://sethnr/pgcoe_bacseq:0.01"
    log:
        stderr="logs/depth/"+config['runname']+".err"
    shell:
        """
        samtools depth -a -H {input.bams} -o {output} 2>&1 >  {log.stderr}
        """


rule combinedcoverage:
    input:
        coveragestats=expand(os.path.join(config['outdir'],'align/{sample}_coverage_sub{subsample}.tsv'),sample=SAMPLES,subsample=READ_SUBSAMPLES)
    output:
        combinedcoverage=os.path.join(config['outdir'],config['runname'],'combinedcoverage.tsv')
    resources:
        mem_mb=8000,
        runtime=180,
    log:
        stderr="logs/coverage.err"
    shell:
        """
        {{ echo -e "sample\tsubsample\trname\tstartpos\tendpos\tnumreads\tcovbases\tcoverage\tmeandepth\tmeanbaseq\tmeanmapq";cat {input.coveragestats}; }} > {output.combinedcoverage} 2> {log.stderr}
        """

rule indexbam:
    input:
        bam = '{samplename}.bam'
    output:
        indexedbam = '{samplename}.bam.bai'
    container: "docker://sethnr/pgcoe_bacseq:0.01"
    log:
        stdout="logs/bamindex/{samplename}.out",
        stderr="logs/bamindex/{samplename}.err"
    message: "Indexing bam file: {wildcards.samplename}"
    shell:
        """
        samtools index {input.bam} > {log.stdout} 2> {log.stderr}
        """



rule variantcalling:
    input:
        tocall=expand(os.path.join(config['outdir'],'align/{sample}_aln_itrim_sorted.bam'),sample=SAMPLES),
        indexed=expand(os.path.join(config['outdir'],'align/{sample}_aln_itrim_sorted.bam.bai'),sample=SAMPLES)
    params:
        ref=config['reference']
    resources:
        mem_mb=8000,
        runtime=240,
    output:
        vcf=os.path.join(config['outdir'],'pileup',"all_variants_unfilt.vcf.gz")
    log:
        stdout="logs/variantcalling.out",
        stderr="logs/variantcalling.err"
    message: "Calling variants for all samples"
    container: "docker://sethnr/pgcoe_bacseq:0.01"
    shell:
        """
        bcftools mpileup -Ou -o variants.bcf -f {params.ref} {input.tocall} 1> {log.stdout} 2> {log.stderr}
        bcftools call --ploidy 1 -vcO z -o {output.vcf} variants.bcf 1>> {log.stdout} 2>> {log.stderr}
        tabix -p vcf {output.vcf} 1>> {log.stdout} 2>> {log.stderr}
	        
	"""

rule variantfilter:
    input:
        vcf={rules.variantcalling.output.vcf}
    output:
        vcf_filt=os.path.join(config['outdir'],'pileup',"all_variants_filt.vcf.gz")
    resources:
        mem_mb=8000,
        runtime=180,
    log:
        stdout="logs/variantfilter.out",
        stderr="logs/variantfilter.err"
    container: "docker://sethnr/pgcoe_bacseq:0.01"
    shell:
        """
        bcftools filter -O z -o {output.vcf_filt} -i 'QUAL>10 & DP>10' {input.vcf} 1> {log.stdout} 2> {log.stderr}
        """

rule evorha:
    input:
        bam=config['outdir']+'/align/{sample}_aln_itrim_sorted.bam',
        idx=config['outdir']+'/align/{sample}_aln_itrim_sorted.bam.bai',
    params:
        ref=config['reference'],
        bamln=config['outdir']+'/evorha/{sample}_sorted.bam',
        idxln=config['outdir']+'/evorha/{sample}_sorted.bam.bai',
        prefix=config['outdir']+'/evorha/',
        indirs=expand(config['outdir']+'/snippy/snippy_{sample}',sample=SAMPLES)
    resources:
        mem_mb=8000,
        runtime=1440,
    container: "docker://sethnr/pgcoe_evorha:0.01"
    output:
        coreout = config['outdir']+'/evorha/{sample}.hapfreq',
    log:
        stderr="logs/evorha/{sample}.err",
    message: "Running evorha"
    shell:
        """
	    ln -f {input.bam} {params.bamln}
            ln -f {input.idx} {params.idxln}
            java -jar /jars/evorha.jar completeAnalysis {params.ref} {params.bamln} 2>&1 >> {log.stderr}
        """



rule get_metrics:
    input:
        pileupvcf=os.path.join(config['outdir'],'pileup',"all_variants_filt.vcf.gz"),
        #snippyvcf=config['outdir']+'/snippy/core.vcf',
        combinedcoverage=os.path.join(config['outdir'],config['runname'],'combinedcoverage.tsv'),
        depth=config['outdir']+'/'+config['runname']+'/all_depth.txt',
        primers='results/refs/primers.bed',
        amplicons='results/refs/amplicons.bed',
    output:
        #expand(config['outdir']+'/'+config['runname']+'/'+config['runname']+'_{site}_{program}_{metric}.tsv',
        #       program=["pileup","snippy"], site=["primers","amplicons"],metric=["meandp","covpc","pi"]),
        #snippyvcf=config['outdir']+'/'+config['runname']+'/snippy_all_vars.vcf',
        expand(config['outdir']+'/'+config['runname']+'/'+config['runname']+'_{site}_{program}_{metric}.tsv',
               program=["pileup"], site=["primers","amplicons"],metric=["meandp","covpc","pi"]),
        pileupvcf=config['outdir']+'/'+config['runname']+'/pileup_all_vars.vcf.gz',
    container: "docker://sethnr/pgcoe_analysis:0.01"
    resources:
        mem_mb=8000,
        runtime=240,
	    cores=1,
    params:
        spprefix=config['outdir']+'/'+config['runname']+'/'+config['runname']+'_primers_snippy',
        saprefix=config['outdir']+'/'+config['runname']+'/'+config['runname']+'_amplicons_snippy',
        ppprefix=config['outdir']+'/'+config['runname']+'/'+config['runname']+'_primers_pileup',
        paprefix=config['outdir']+'/'+config['runname']+'/'+config['runname']+'_amplicons_pileup',
    shell:
        """
	    cp {input.pileupvcf} {output.pileupvcf}
        python scripts/get_pidp_ranges.py --vcf {input.pileupvcf} --depth {input.depth} --bed {input.primers} --out {params.ppprefix}
        python scripts/get_pidp_ranges.py --vcf {input.pileupvcf} --depth {input.depth} --bed {input.amplicons} --out {params.paprefix}
        """
