import pandas as pd
import os

configfile: "config/config.yaml"

SAMPLES = [line.strip() for line in open(config['samples'], 'r')]


HOST = config['hostname']
TARGET = config['refname']

include: "rules/cplocal.smk"
include: "rules/align.smk"
include: "rules/stats.smk"

wildcard_constraints:
    sample="[^_]+",
    target="[^_]+",
    host="[^_]+"


localrules: all, cp_local_fq


rule all:
    input:
        expand(os.path.join('results/clean/{sample}_'+HOST+'_R1.fastq.gz'),sample=SAMPLES),
        expand(os.path.join('results/clean/{sample}_'+HOST+'_R2.fastq.gz'),sample=SAMPLES),
        expand(os.path.join(config['outdir'],'align/{sample}_'+TARGET+'.bam'),sample=SAMPLES),
        'results/stats/'+TARGET+'_'+HOST+'_alignstats.txt'

